Repository asgardeo/thunder, pull requests merged in 2025-10, with the labels that each got.

#437 Update hash usage
  backend/internal/notification/otpservice.go
Labels: Type/Bug

#440 Add jwt verify methods and fix usages
  backend/internal/authn/oidc/service.go
  backend/internal/notification/otpservice.go
  backend/internal/oauth/oauth2/authz/authzhandler.go
  backend/internal/oauth/oauth2/granthandlers/refreshtoken.go
  backend/internal/oauth/oauth2/introspect/service.go
  backend/internal/oauth/oauth2/introspect/service_test.go
  backend/internal/system/jwt/service.go
  backend/internal/system/jwt/service_test.go
  backend/tests/mocks/database/providermock/DBClientInterface_mock.go
  backend/tests/mocks/database/providermock/DBProviderInterface_mock.go
  backend/tests/mocks/jwtmock/JWTServiceInterface_mock.go
Labels: Type/Bug

#447 Improve secret properties handling
  backend/internal/authn/oauth/utils.go
  backend/internal/flow/utils/utils.go
  backend/internal/idp/handler.go
  backend/internal/idp/model.go
  backend/internal/idp/service.go
  backend/internal/idp/store.go
  backend/internal/notification/common/model.go
  backend/internal/notification/message/customclient.go
  backend/internal/notification/message/twilioclient.go
  backend/internal/notification/message/vonageclient.go
  backend/internal/notification/messagehandler.go
  backend/internal/notification/store.go
  backend/internal/notification/utils.go
  backend/internal/system/cmodels/property.go
Labels: Type/Improvement

#446 Add federated IDP authentication API and service implementation
  backend/internal/authn/common/model.go
  backend/internal/authn/errorconstants.go
  backend/internal/authn/google/service.go
  backend/internal/authn/handler.go
  backend/internal/authn/model.go
  backend/internal/authn/oidc/service.go
  backend/internal/authn/service.go
  backend/internal/system/managers/servicemanager.go
  backend/internal/system/services/authenticationservice.go
  docs/apis/authentication.yaml
Labels: Type/New Feature
