Repository asgardeo/thunder, pull requests merged in 2025-09, with the labels that each got.

#349 Fix release workflow to bump product version
  .github/workflows/release.yml
Labels: skip-changelog

#351 Improve default config handling with a default.json file
  backend/cmd/server/main.go
  backend/cmd/server/repository/conf/deployment.yaml
  backend/cmd/server/repository/resources/conf/default.json
  backend/internal/application/service/applicationservice.go
  backend/internal/executor/authassert/authassertexecutor.go
  backend/internal/oauth/oauth2/granthandlers/authorizationcode.go
  backend/internal/oauth/oauth2/granthandlers/clientcredentials.go
  backend/internal/oauth/oauth2/granthandlers/refreshtoken.go
  backend/internal/oauth/oauth2/granthandlers/refreshtoken_test.go
  backend/internal/system/cache/cache.go
  backend/internal/system/cache/cache_test.go
  backend/internal/system/cache/constants.go
  backend/internal/system/cache/inmemorycache.go
  backend/internal/system/cache/inmemorycache_test.go
  backend/internal/system/cache/manager.go
  backend/internal/system/cache/manager_test.go
  backend/internal/system/config/config.go
  backend/internal/system/config/config_test.go
  backend/internal/system/jwt/service.go
  backend/internal/system/jwt/service_test.go
  backend/internal/system/jwt/utils.go
  backend/internal/system/jwt/utils_test.go
Labels: Type/New Feature

#357 Improve caching in 'allowed origins'
  backend/internal/system/server/serveroperation.go
Labels: Type/Improvement

#358 Update release change list heading emoji
  .github/workflows/release.yml
Labels: skip-changelog

#354 Improve auth assertion to use application token configurations
  backend/internal/authn/dto/dto.go
  backend/internal/executor/attributecollect/attributecollector.go
  backend/internal/executor/authassert/authassertexecutor.go
  backend/internal/executor/basicauth/basicauthexecutor.go
  backend/internal/executor/githubauth/githubauthexecutor.go
  backend/internal/executor/oauth/oauthexecutor.go
  backend/internal/executor/oidcauth/oidcauthexecutor.go
  backend/internal/executor/provision/provisioningexecutor.go
  backend/internal/executor/smsauth/smsauthexecutor.go
  backend/internal/flow/constants/errorconstants.go
  backend/internal/flow/engine/flowengine.go
  backend/internal/flow/flowexecservice.go
  backend/internal/flow/model/flowmodel.go
  backend/internal/flow/store/model.go
  backend/internal/oauth/session/store/sessiondatastore_test.go
  backend/internal/system/utils/sliceutil.go
Labels: Type/Improvement

#363 Introduce user schema enforcement to the user operations
  backend/internal/system/database/utils/querybuilder.go
  backend/internal/user/constants/errorconstants.go
  backend/internal/user/handler/userhandler.go
  backend/internal/user/service/userservice.go
  backend/internal/userschema/constants/errorconstants.go
  backend/internal/userschema/service/userschemaservice.go
  tests/integration/userschema/model.go
  tests/integration/userschema/user_tree_validation_test.go
  tests/integration/userschema/user_uniqueness_test.go
  tests/integration/userschema/user_validation_edge_cases_test.go
  tests/integration/userschema/user_validation_test.go
Labels: Type/Improvement

#369 Add basic filter support for user listing
  backend/internal/user/constants/errorconstants.go
  backend/internal/user/handler/userhandler.go
  backend/internal/user/service/userservice.go
  backend/internal/user/store/queries.go
  backend/internal/user/store/store.go
  backend/tests/mocks/user/servicemock/UserServiceInterface_mock.go
  docs/apis/user.yaml
  tests/integration/user/user_filter_test.go
  tests/integration/user/userapi_test.go
Labels: Type/Improvement

#371 Update Docker image to add user ID and group ID
  Dockerfile
Labels: Type/Improvement

#372 Update release workflow to package macOS sample app
  .github/workflows/release.yml
Labels: skip-changelog

#375 Disable automatic version update in release workflow
  .github/workflows/release.yml
Labels: skip-changelog

#376 Update release-drafter to disable 'other changes'
  .github/release-drafter.yml
Labels: skip-changelog

#385 Fix release drafter and add pre-release input
  .github/release-drafter.yml
  .github/workflows/release.yml
Labels: skip-changelog

#387 Prepare for the next version
  samples/apps/oauth/package-lock.json
  samples/apps/oauth/package.json
  samples/apps/oauth/server/package-lock.json
  samples/apps/oauth/server/package.json
  version.txt
Labels: skip-changelog

#378 Add Helm Chart for Thunder Kubernetes Deployment
  install/helm/.helmignore
  install/helm/Chart.yaml
  install/helm/README.md
  install/helm/conf/deployment.yaml
  install/helm/templates/_helpers.tpl
  install/helm/templates/config-map.yaml
  install/helm/templates/hpa.yaml
  install/helm/templates/ingress.yaml
  install/helm/templates/pdb.yaml
  install/helm/templates/rbac.yaml
  install/helm/templates/service-account.yaml
  install/helm/templates/service.yaml
  install/helm/templates/thunder-deployment.yaml
  install/helm/values.yaml
Labels: Type/New Feature

#390 Add support to define required attributes in user-schema
  backend/internal/userschema/service/userschemaservice.go
  docs/apis/user.yaml
  tests/integration/userschema/userschema_api_create_test.go
  tests/integration/userschema/userschema_api_delete_test.go
  tests/integration/userschema/userschema_api_get_test.go
  tests/integration/userschema/userschema_api_update_test.go
  tests/integration/userschema/userschema_required_api_test.go
Labels: Type/Improvement

#393 Update README to indicate Go version requirement as 1.25
  README.md
Labels: Type/Bug

#394 Fix redundant file reads on tls config and cert kid handling
  backend/cmd/server/main.go
  backend/internal/cert/systemcertservice.go
  backend/internal/oauth/jwks/constants/constants.go
  backend/internal/oauth/jwks/service.go
  backend/internal/oauth/jwks/service_test.go
  backend/internal/system/config/runtimeconfig.go
  backend/internal/system/jwt/service.go
  backend/internal/system/jwt/service_test.go
  backend/tests/mocks/certmock/SystemCertificateServiceInterface_mock.go
Labels: Type/Improvement

#399 Parameterize readOnlyRootFilesystem and update readme
  install/helm/README.md
  install/helm/templates/thunder-deployment.yaml
  install/helm/values.yaml
Labels: Type/Improvement

#395 Centralizing DB Client creation and closing & Introduce database connection pooling
  backend/cmd/server/repository/conf/deployment.yaml
  backend/cmd/server/repository/resources/conf/default.json
  backend/internal/application/store/store.go
  backend/internal/cert/store/store.go
  backend/internal/flow/store/store.go
  backend/internal/group/store/store.go
  backend/internal/idp/store/store.go
  backend/internal/notification/message/store/store.go
  backend/internal/oauth/oauth2/authz/store/store.go
  backend/internal/oauth/oauth2/authz/store/store_test.go
  backend/internal/ou/store/store.go
  backend/internal/system/config/config.go
  backend/internal/system/database/provider/dbclient.go
  backend/internal/system/database/provider/dbclient_test.go
  backend/internal/system/database/provider/dbprovider.go
  backend/internal/system/healthcheck/service/healthcheckservice.go
  backend/internal/system/healthcheck/service/healthcheckservice_test.go
  backend/internal/user/store/store.go
  backend/internal/userschema/store/store.go
  backend/tests/mocks/database/providermock/DBProviderInterface_mock.go
  install/helm/values.yaml
Labels: Type/Improvement

#400 Refactor dbprovider to reduce code duplication
  backend/internal/system/database/provider/dbprovider.go
Labels: Type/Improvement

#401 Improve makefile
  Makefile
Labels: skip-changelog

#420 Add encryption to secret properties in identity providers and notification senders
  backend/dbscripts/thunderdb/postgres.sql
  backend/dbscripts/thunderdb/sqlite.sql
  backend/internal/flow/utils/utils.go
  backend/internal/idp/handler/handler.go
  backend/internal/idp/model/model.go
  backend/internal/idp/service/idpservice.go
  backend/internal/idp/store/constants.go
  backend/internal/idp/store/store.go
  backend/internal/notification/common/model.go
  backend/internal/notification/message/customclient.go
  backend/internal/notification/message/twilioclient.go
  backend/internal/notification/message/vonageclient.go
  backend/internal/notification/messagehandler.go
  backend/internal/notification/store.go
  backend/internal/notification/storeconstants.go
  backend/internal/notification/utils.go
  backend/internal/system/cmodels/property.go
  tests/integration/resources/dbscripts/thunderdb/sqlite.sql
Labels: Type/Improvement

#428 Add OIDC and Google auth core services
  backend/internal/authn/google/constants.go
  backend/internal/authn/google/errors.go
  backend/internal/authn/google/service.go
  backend/internal/authn/oidc/constants.go
  backend/internal/authn/oidc/errors.go
  backend/internal/authn/oidc/service.go
  backend/internal/executor/googleauth/googleauthexecutor.go
  backend/internal/executor/oidcauth/oidcauthexecutor.go
Labels: Type/Improvement

#433 Refactor the IDP package/ service
  backend/internal/authn/oauth/service.go
  backend/internal/authn/oauth/utils.go
  backend/internal/executor/githubauth/githubauthexecutor.go
  backend/internal/executor/googleauth/googleauthexecutor.go
  backend/internal/executor/oauth/oauthexecutor.go
  backend/internal/executor/oidcauth/oidcauthexecutor.go
  backend/internal/flow/utils/utils.go
  backend/internal/idp/errorconstants.go
  backend/internal/idp/handler.go
  backend/internal/idp/model.go
  backend/internal/idp/service.go
  backend/internal/idp/store.go
  backend/internal/idp/storeconstants.go
  backend/internal/system/services/idpservice.go
Labels: Type/Improvement
